### ISSUE TITLE
Missing UI elements

### ISSUE THREAD

**Issue by dailja21** [Oht0nger/PhoLabeler#1]
Initial window after opening the program is not maximized. If the maximize button is clicked before the UI elements are finished loading, sometimes they don't load - for example the Track information panel and the buttons above it will not load.

**Comment by Oht0nger** [comment]
Thank you very much for finding time to provide feedback on the software. The incomplete loading could attributed the slow AppDesigner environment used to create the tool. I will check if there any fixes or workaround to this issue.

**Comment by dailja21** [comment]
And thank you very much for creating this program. I've been using it daily over the past few weeks, so I've been able to take note of recurring bugs.

**Comment by Oht0nger** [comment]
I am glad you are using the tool and providing feedback on issues!
