### ISSUE TITLE
Load Session not working

### ISSUE THREAD

**Issue by dailja21** [Oht0nger/PhoLabeler#2]
File -> Load Session has never worked for me.

**Comment by Oht0nger** [comment]
Please send me the error log so I can see what is causing the error.

**Comment by dailja21** [comment]
Sorry I should have been more specific. When I click File -> Load Session, nothing happens.

**Comment by Oht0nger** [comment]
You are right, I forgot to add the functionality to that menu. Please use the button above the track information.
