### ISSUE TITLE
Map refresh issue

### ISSUE THREAD

**Issue by dailja21** [Oht0nger/PhoLabeler#4]
After clicking the "step forward' button a few times, I often find that I have to close the map and reopen to get it to correctly display the transect.

There is also an issue with point labeling. After selecting points for labeling, the map seems to refresh for some reason, leaving you unable to select anything for a few seconds, which really adds up over time. To workaround this, I select the points for labeling, turn off the map and turn it back on, and repeat the process. This is faster than waiting for the map to finish refreshing on its own.

**Comment by Oht0nger** [comment]
"To workaround this, I select the points for labeling, turn off the map and turn it back on, and repeat the process. This is faster than waiting for the map to finish refreshing on its own." Please continue to do this as we look into ways of improving it.
