### ISSUE TITLE
Mouse click registering time

### ISSUE THREAD

**Issue by dailja21** [Oht0nger/PhoLabeler#5]
I've noticed on some buttons (i.e. rectangle selection button, map button, step forward/backward button), if you click and move the mouse away too quickly, the mouse click will not register - so I have to place the mouse over the button, click, wait 1-2 seconds, then continue working.

**Comment by Oht0nger** [comment]
This again might be attributable to the slow AppDesigner environment. I will also check my code to disable wait statements, if any. Thanks once more for reaching out. Let me know if there any other issues you are experiencing.
