### ISSUE TITLE
Selection tool cursor

### ISSUE THREAD

**Issue by dailja21** [Oht0nger/PhoLabeler#6]
Sometimes when clicking the selection tool (I almost always use the rectangle selection tool), the cursor becomes a cross-hair and sometimes the cursor is a hand. I can upload screenshots of any of these issues if that will help.

**Comment by Oht0nger** [comment]
I have see that issue. Sometimes the pan and zoom functions within the Detail plot get active, so if you see a hand just hit ESC before using the rectangular tool.
