### ISSUE TITLE
Map refresh issue #2

### ISSUE THREAD

**Issue by dailja21** [Oht0nger/PhoLabeler#7]
With the map open, and after finishing labeling one section and clicking step forward, the map does not update the location of the transect - the previous position continues to be displayed. To correct this, I have to turn off the map and turn back on. It happens so often that I typically label points, turn off map, step forward, turn on map, label points, and repeat.

**Comment by Oht0nger** [comment]
Yes, that's a known issue created by the way MATLAB queues requests between the main interface and the webmap. It is recommend to disable the webmap if you have to skip through many segments to avoid this lag
