### ISSUE TITLE
Map zoom

### ISSUE THREAD

**Issue by dailja21** [Oht0nger/PhoLabeler#8]
Is it possible to zoom in more on the map?

**Comment by Oht0nger** [comment]
Yes, you can! You can use mouse wheel to zoom in and out. When data is loaded, you also have an active drop-down menu in the upper right corner of the detail plot

**Comment by dailja21** [comment]
Sorry I mean if it's possible to zoom in even more. In the web map in the top left, there is one more zoom level that cannot be used - it says 'Map data not yet available'. I wasn't sure if there are different map services that allow you to zoom in more.

Also, often multiple web browser tabs will open - lets say you click 'step forward', label points, 'step forward', label points, repeat - eventually multiple tabs will open for some reason - each with a map of the transect.

One more issue - as of updating Windows 10 to version 20H2, I seem to have more issues with the transect not updating its location in the map when using the 'step forward/step back' - might just be a coincidence from when I updated windows - not sure.

**Comment by Oht0nger** [comment]
The zoom level depends on the image data available in the web map. In most places over the US, one can zoom to high resolution content but other places do not have content. So when you get  'Map data not yet available', it means there is no  corresponding image data at that zoom level. Thanks again for your feedback on the software!

**Comment by dailja21** [comment]
Thank you for the response 👍
